require "spec_helper"

describe Jekyll::PostFiles do
  let(:page)      { make_page }
  let(:site)      { make_site }
  let(:post)      { make_post }
  let(:context)   { make_context(:page => page, :site => site) }
  let(:url)       { "" }

  before do
    Jekyll.logger.log_level = :error
    site.process
  end

  it "copies image from global assets folder" do
    expect(Pathname.new(File.expand_path('assets/jekyll.png', dest_dir))).to exist
  end

  it "copies image from post folder" do
    expect(Pathname.new(File.expand_path('2016/06/09/cloudflare.png', dest_dir))).to exist
  end

  it "Static files have the right classes when generated by PostFiles" do
    expect(site.static_files[1].name.class).to eq site.static_files[0].name.class
    expect(site.static_files[1].destination_rel_dir.class).to eq site.static_files[0].destination_rel_dir.class
    expect(site.static_files[1].path.class).to eq site.static_files[0].path.class
    expect(site.static_files[1].basename.class).to eq site.static_files[0].basename.class
    expect(site.static_files[1].cleaned_relative_path.class).to eq site.static_files[0].cleaned_relative_path.class
    expect(site.static_files[1].to_liquid.class).to eq site.static_files[0].to_liquid.class
  end
end
